import os
from dotenv import load_dotenv
 
load_dotenv()

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_USERNAME = os.getenv("REDIS_USERNAME") or "default"
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
REDIS_DATABASE = os.getenv("REDIS_DATABASE") or 0
REDIS_PROTOCOL = os.getenv("REDIS_PROTOCOL") or "redis"

REDIS_URL = "{}://default:{}@{}:{}/{}".format(
    REDIS_PROTOCOL, REDIS_PASSWORD, REDIS_HOST, REDIS_PORT, REDIS_DATABASE
)

ANALYTICS_CENTRAL_DATABASE_PORT = os.getenv("ANALYTICS_CENTRAL_DATABASE_PORT")
ANALYTICS_CENTRAL_DATABASE_HOST = os.getenv("ANALYTICS_CENTRAL_DATABASE_HOST")
ANALYTICS_CENTRAL_DATABASE_NAME = os.getenv("ANALYTICS_CENTRAL_DATABASE_NAME")
ANALYTICS_CENTRAL_DATABASE_USERNAME = os.getenv("ANALYTICS_CENTRAL_DATABASE_USERNAME")
ANALYTICS_CENTRAL_DATABASE_PASSWORD = os.getenv("ANALYTICS_CENTRAL_DATABASE_PASSWORD")

ANALYTICS_CENTRAL_DATABASE_URL = f"postgresql://{ANALYTICS_CENTRAL_DATABASE_USERNAME}:{ANALYTICS_CENTRAL_DATABASE_PASSWORD}@{ANALYTICS_CENTRAL_DATABASE_HOST}:{ANALYTICS_CENTRAL_DATABASE_PORT}/{ANALYTICS_CENTRAL_DATABASE_NAME}"